### ISSUE TITLE
Failed prop type: Invalid prop `d` supplied to `AnimateSVG`

### ISSUE THREAD

**Issue by vprtsingh** [Hestabit/react-native-svg-animate#5]
**Unable to implement** 

    import React, {Component} from 'react';
    import { StyleSheet, View} from 'react-native';
    import { AnimateSVG } from '@hestabit/react-native-svg-animate'

    export default class App extends Component {
  	render() {
    	return (
			<View>
				<AnimateSVG
					strokeWidth={3}
					duration={2000}
					height={512}
					scale={1}
					width={512}
					viewBox={"-59 0 512 512"}
					d={require("./city.svg")}
					type={"async"}
					animEffect={"bounce"}
					ref={ref => (this._animateSVG = ref)}
				/>
			</View>
    	);
  	}
    }

![animate-svg-error](https://user-images.githubusercontent.com/30243861/59828453-b08dd100-9358-11e9-89d4-01392109398a.png)

**Comment by Mr-Bhardwa7** [comment]
Hello @vprtsingh,
You need to pass the svg path in this `d` props instead of complete svg.
It can be single path in `string` or multiple path in `array of string`.

**example** 
`const singlePath = 'M10 10 L150 10 L150 70 L10 70 L10 10 z'`

```
const multiplePath = [
  'M498.465,1L1,288.188',
  'M600.984,288.188L103.53,1',
  'M462.988,601V1',
  'M107.176,601l493.651-285',
]
```

```
 <AnimateSVG
        strokeWidth={3}
        duration={2000}
        height={512}
        scale={1}
        width={512}
        d={multiplePath}
        viewBox={"-59 0 512 512"}
        type={"async"}
        animEffect={"bounce"}
        ref={ref => (this._animateSVG = ref)}
 />
```

**Comment by vprtsingh** [comment]
Thanks @Mr-Bhardwa7 it's working now
